### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by DanielAndreasen** [j-faria/pySWEETCat#1]
Hi João,

Hope everything is well :)
Not sure what this package will do, but are you aware of [this method](https://github.com/sczesla/PyAstronomy/blob/master/src/pyasl/resBased/sweet_cat.py) in `PyAstronomy`? It might do what you want to do.

**Comment by j-faria** [comment]
Yes I'm aware, thank you :)
I wanted to do a pure Python version, and I used it as an example in the Python course last week.
Not much else to see here... 

PS: see you next week!

**Comment by DanielAndreasen** [comment]
Well, looks great :) See you in a week.
